import '../models/ecole_model.dart';
import '../models/metier.dart';

class MockData {
  static const List<Metier> metiers = [
    Metier(
      id: 1,
      nom: 'Développeur Web',
      description: 'Conçoit et développe des applications web modernes, performantes et accessibles.',
      salaireMoyen: SalaireMetier(minimum: 28000, moyen: 42000, maximum: 65000),
      competencesRequises: ['Flutter', 'JavaScript', 'UI responsive'],
      filieresEtudes: ['BUT Informatique', 'Licence informatique', 'Master développement web'],
      dureeEtudes: '3 à 5 ans',
      ecolesRecommandees: ['Epitech', '42', 'Université Paris Cité'],
      icone: 'engineering',
      roadmap: RoadmapMetier(
        diplomeRequis: 'Bac+3 à Bac+5',
        competencesAApprendre: ['Git', 'API REST', 'Architecture logicielle'],
        experiencesRecommandees: ['Stage web', 'Projet freelance', 'Hackathons'],
      ),
      domaine: 'Technologie',
      niveauRequis: 'Bac+3',
    ),
    Metier(
      id: 2,
      nom: 'Médecin',
      description: 'Diagnostique et soigne les patients au sein de structures de santé publiques ou privées.',
      salaireMoyen: SalaireMetier(minimum: 36000, moyen: 70000, maximum: 120000),
      competencesRequises: ['Anatomie', 'Empathie', 'Rigueur'],
      filieresEtudes: ['PASS', 'LAS', 'Internat de médecine'],
      dureeEtudes: '6+ ans',
      ecolesRecommandees: ['Sorbonne Université', 'Université de Lyon'],
      icone: 'health',
      roadmap: RoadmapMetier(
        diplomeRequis: 'Doctorat en médecine',
        competencesAApprendre: ['Diagnostic clinique', 'Urgences', 'Communication patient'],
        experiencesRecommandees: ['Externat', 'Internat hospitalier'],
      ),
      domaine: 'Santé',
      niveauRequis: 'Bac+5',
    ),
    Metier(
      id: 3,
      nom: 'Designer Graphique',
      description: 'Crée des identités visuelles, interfaces et supports de communication numériques.',
      salaireMoyen: SalaireMetier(minimum: 25000, moyen: 38000, maximum: 52000),
      competencesRequises: ['Figma', 'Photoshop', 'Typographie'],
      filieresEtudes: ['DN MADE', 'École de design', 'Licence arts visuels'],
      dureeEtudes: '3 ans',
      ecolesRecommandees: ['Gobelins', 'Strate École de Design'],
      icone: 'palette',
      roadmap: RoadmapMetier(
        diplomeRequis: 'Bac+3',
        competencesAApprendre: ['Branding', 'Motion design', 'UX design'],
        experiencesRecommandees: ['Portfolio projets', 'Alternance en agence'],
      ),
      domaine: 'Créatif',
      niveauRequis: 'Bac+3',
    ),
    Metier(
      id: 4,
      nom: 'Data Analyst',
      description: 'Analyse les données pour aider les entreprises à prendre des décisions stratégiques.',
      salaireMoyen: SalaireMetier(minimum: 32000, moyen: 47000, maximum: 68000),
      competencesRequises: ['SQL', 'Power BI', 'Statistiques'],
      filieresEtudes: ['Licence mathématiques', 'Master data'],
      dureeEtudes: '5 ans',
      ecolesRecommandees: ['ESILV', 'Université Paris-Saclay'],
      icone: 'science',
      roadmap: RoadmapMetier(
        diplomeRequis: 'Bac+5',
        competencesAApprendre: ['Python', 'Data visualisation', 'Modélisation'],
        experiencesRecommandees: ['Projet data', 'Stage BI'],
      ),
      domaine: 'Business',
      niveauRequis: 'Bac+5',
    ),
    Metier(
      id: 5,
      nom: 'Architecte',
      description: 'Conçoit des bâtiments fonctionnels et durables en lien avec les besoins urbains.',
      salaireMoyen: SalaireMetier(minimum: 30000, moyen: 45000, maximum: 75000),
      competencesRequises: ['CAO', 'Urbanisme', 'Gestion de projet'],
      filieresEtudes: ['École nationale d\'architecture', 'HMONP'],
      dureeEtudes: '5 ans',
      ecolesRecommandees: ['ENSA Paris-Belleville', 'ENSA Lyon'],
      icone: 'business',
      roadmap: RoadmapMetier(
        diplomeRequis: 'Bac+5',
        competencesAApprendre: ['Rendu 3D', 'Normes environnementales'],
        experiencesRecommandees: ['Stage en cabinet', 'Concours architecture'],
      ),
      domaine: 'Ingénierie',
      niveauRequis: 'Bac+5',
    ),
  ];

  static const List<EcoleModel> ecoles = [
    EcoleModel(
      id: 1,
      nom: 'Epitech Paris',
      ville: 'Paris',
      type: 'Grande école',
      domaines: ['Technologie', 'Ingénierie'],
      filieres: ['Informatique', 'Cybersécurité'],
      logoUrl: '',
    ),
    EcoleModel(
      id: 2,
      nom: 'Université de Lyon',
      ville: 'Lyon',
      type: 'Université',
      domaines: ['Santé', 'Business'],
      filieres: ['Médecine', 'Économie'],
      logoUrl: '',
    ),
    EcoleModel(
      id: 3,
      nom: 'Gobelins',
      ville: 'Paris',
      type: 'Institut',
      domaines: ['Créatif'],
      filieres: ['Design Graphique', 'Animation'],
      logoUrl: '',
    ),
    EcoleModel(
      id: 4,
      nom: 'ESILV',
      ville: 'La Défense',
      type: 'Grande école',
      domaines: ['Technologie', 'Business'],
      filieres: ['Data', 'Ingénierie financière'],
      logoUrl: '',
    ),
  ];
}
